version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=dev_user
      - POSTGRES_DB=talkhub_db
    ports:
      - '5434:5432'

  redis:
    image: redis:latest
    ports:
      - '6379:6379'