# Generated by Django 4.2.4 on 2023-08-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_populate_tables_with_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailconfirmationcode",
            name="expiration",
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="followings",
            field=models.ManyToManyField(
                blank=True, related_name="profiles", related_query_name="profile", to="accounts.profile"
            ),
        ),
    ]
