# Generated by Django 4.2.4 on 2023-08-25 18:13

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_populate_tables_with_defaults"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("cf3c1361-b838-47f3-854b-9d076ed6b1ff"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
