# Generated by Django 4.2.4 on 2023-08-16 23:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_emailconfirmationcode_expiration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="about",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
