# Generated by Django 4.2.4 on 2023-08-28 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_config_user_alter_tweet_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="parent_tweet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tweets",
                related_query_name="tweet",
                to="core.tweet",
            ),
        ),
    ]
