# Generated by Django 4.2.4 on 2023-08-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_tweet_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationtype",
            name="name",
            field=models.CharField(max_length=7, unique=True, verbose_name="notification type"),
        ),
    ]
