# Generated by Django 4.2.4 on 2023-08-28 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0004_alter_tweet_parent_tweet"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="users",
            new_name="recipients",
        ),
        migrations.AddField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_ratings",
                related_query_name="notification_rating",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="text",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
