# Generated by Django 4.2.4 on 2023-08-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="config",
            name="tweets_order",
            field=models.CharField(max_length=20),
        ),
    ]
