# Generated by Django 4.2.4 on 2023-08-30 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_retweet_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="retweet_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
